### ISSUE TITLE
Windows Borderless 모드에서 악성코드 발견

### ISSUE THREAD

**Issue by No-Eul** [MaGyul/MTW-Launcher#3]
[Malware Discovery Disclosure: "Windows Borderless" mod](https://blog.modrinth.com/p/windows-borderless-malware-disclosure)

**Comment by MaGyul** [comment]
모드를 적용할 예정을 하고 등록만 시켰을 뿐 실행된적이 없어서 다행이네요.
갑자기 모드가 없어져서 해당 모드에 뭔 일이 있나 했는데 악성코드 였군요.

이슈를 해주셔서 감사합니다.
